services:
  init:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/workspace
    command:
      - /bin/bash
      - -c
      - |
        airflow db migrate
        echo "{\"admin\": \"${AIRFLOW_PASSWORD}\"}" > /workspace/airflow/simple_auth_manager_passwords.json.generated
        python3 init_db.py
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 50000:8080
    volumes:
      - .:/workspace
    command: airflow standalone
