services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - ./db:/db
    command: airflow standalone
