services:
  init:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - 8080
    volumes:
      - .:/workspace
    command:
      - /bin/bash
      - -c
      - |
        airflow db migrate
        echo "{\"admin\": \"${AIRFLOW_PASSWORD}\"}" > /workspace/airflow/simple_auth_manager_passwords.json.generated
        python3 init_db.py
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - 8080
    volumes:
      - .:/workspace
    command:
      - /bin/bash
      - -c
      - 'airflow api-server --port 8080 & airflow scheduler & airflow dag-processor & airflow triggerer'
